require('settings')
require('packer-config')
-- require('colorschemes-config.duskfox')
require('colorschemes-config')
require('nvim-tree-config')
require('mappings')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('lsp-config.language_servers')
require('lsp-config.nvim-cmp')
require('lsp-config.diagnostic_signs')
require('git-config')
require('null-ls-config')
require('blackline-config')
require('comment-config')
require('colorizer-config')
